#!/bin/bash

#Aluno: Jefferson Felix Gomes
#Matrícula: 1510010879

#Criando diretótio
echo "Criando diretório, digite um nome Ex:exercicio"
read DIRE
mkdir ~/$DIRE
echo "Diretório criado" >> ~/$DIRE/log

#Criando arquivo
echo "Criando arquivo digite um nome Ex:arquivo"
read ARQUI
touch ~/$DIRE/$ARQUI
echo "Arquivo criado" >> ~/$DIRE/log

#Escrevendo no arquivo
echo "Escrevendo no arquivo"
date >> ~/$DIRE/$ARQUI
echo "Resumo do arquivo:" >> ~/$DIRE/log
head ~/$DIRE/$ARQUI >> ~/$DIRE/log

#Registro de execução
touch ~/$DIRE/log_`date "+%d-%m-%Y-%H:%M:%S"`.txt

#Empacotar; compactar; mover e criando variável
DATE_ED=`date "+%d-%m-%Y"`
export DATE_ED
tar -zcvf log_$DATE_ED.tgz ~/$DIRE/log_`date "+%d-%m-%Y-%H:%M:%S"`.txt
mv log_$DATE_ED.tgz /home/jefferson 
echo "Finalizando o script"

